# Generated by Django 4.1.7 on 2023-02-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='material',
            name='area',
            field=models.TextField(null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
