# Generated by Django 4.1.7 on 2023-02-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0002_remove_material_descripcion_material_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='area',
            field=models.CharField(max_length=30, null=True, verbose_name='Area'),
        ),
    ]
