# Generated by Django 4.1.7 on 2023-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0003_alter_material_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo')),
                ('detalles', models.TextField(max_length=100, verbose_name='Detalles')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad solicitada')),
            ],
        ),
    ]
