# Generated by Django 4.1.7 on 2023-03-09 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTest', '0004_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='id_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='AppTest.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
